ARG NODE_VERSION=24.21.0
FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

ARG NODE_ENV=development
ARG NEXT_PUBLIC_BACKEND_URL=http://localhost:8000/api/

ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

RUN node --version && npm --version

EXPOSE 3000

CMD ["npm", "run", "dev"]
